language: python
python:
    - "3.6"
# command to install dependencies:
install:
    - pip install -r requirements-dev.txt
# command to run build (perhaps just tests):
script:
    - nosetests gcallah/indras_net/indra2/tests/test_*.py
